### ISSUE TITLE
Connect with oauth

### ISSUE THREAD

**Issue by Zyles** [keevitaja/keeper-laravel#1]
Hi, I'm looking for a ACL system for Laravel for use in our APIs which can work with a identity server (oauth2). Here we store all our user data.

How would one connect this? We do not use Sentry or any other user management on the application itself.

**Comment by keevitaja** [comment]
Hi,

keeper doesn't do much. it only adds roles and permissions to the laravels eloquent auth driver.

google for "laravel oauth2" and you get many github repos in the first results which should do the job.
